services:
  - riak
language: elixir
elixir:
    - 1.2.1
otp_release:
    - 18.0
sudo: false
env:
    - quantum_config_path=quantum.exs
    - collect_target_path=target_repos.exs
script:
    - mix test
    - mix credo
